### ISSUE TITLE
Action fails if saving cache fails

### ISSUE THREAD

**Issue by s-weigand** [pre-commit/action#53] opened 2020-10-12 11:19 UTC
First of all thanks for this action 😄 

Today I had my [pre-commit job failing](https://github.com/s-weigand/flake8-nb/runs/1241477011), with the following error, which isn't fixable by rerunning the job:
```
Error: reserveCache failed: Cache already exists. Scope: refs/pull/80/merge, Key: pre-commit-2-b76e203571a33b83fd824866e8e8daaeda30555cba9e70eb155d9e5310e578b8-7365e065f5f4ed7e591c7e54ee4f8c40d559f8ff4d40fb8fc9eec5d1a9d2e11c, Version: 28cdb9f5496f334116f23e86f0063f5d3a9348c2e22425a33171e071aadada7e
```

My best guess is, that this caused by a corrupted cache, where a cache entry with the key exists, but `cache.restoreCache` is unable to restore it properly (maybe `on: push` and `on: pull_request` wanted to save the cache at the same time? 😵 ). 
So this might be a very rare and quite impossible to reproduce case.

Anyway, since the cache is nice and all, but not a key feature, IMHO it would be reasonable to catch errors caused by `cache.saveCache` and give users a warning ( `core.warning`), instead of letting it bubble up to `core.setFailed`.
https://github.com/pre-commit/action/blob/763fbafdffca49ae97893be3e08a1cf96f2af95f/index.js#L87

Also, there have been some [changes to `@actions/cache`](https://github.com/actions/toolkit/blob/main/packages/cache/RELEASES.md) since [version 0.2.1 which you use](https://github.com/pre-commit/action/blob/763fbafdffca49ae97893be3e08a1cf96f2af95f/package-lock.json#L6), so running `npm upgrade` might improve this action as well.

**Comment by asottile** [comment] 2020-10-12 15:13
dupe of #41 -- I'm not sure there's anything that can be done but feel free to send a PR if you think there is

**Closed by asottile** 2020-10-12 15:13 UTC
